# Generated by Django 5.0 on 2026-05-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='NEW', max_length=20)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('email_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('classification_method', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('classification_tokens', models.IntegerField(blank=True, null=True)),
                ('extraction_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('rfc_message_id', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=500, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='NEW', max_length=20)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('email_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('classification_method', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('classification_tokens', models.IntegerField(blank=True, null=True)),
                ('extraction_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('rfc_message_id', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=500, null=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.emaillog')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('teams_sent', models.BooleanField(default=False)),
                ('teams_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.emaillog')),
                ('reply_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.replyemail')),
            ],
        ),
        migrations.CreateModel(
            name='SkipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('skip_reason', models.CharField(max_length=50)),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['skipped_at'], name='core_skiplo_skipped_5b8529_idx')],
            },
        ),
    ]
