# Generated by Django 5.0 on 2026-04-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='NEW', max_length=20)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('bol_number', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.emaillog')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('teams_sent', models.BooleanField(default=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.emaillog')),
            ],
        ),
    ]
