# Generated by Django 5.0 on 2026-05-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='NEW', max_length=20)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('email_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('classification_method', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('classification_tokens', models.IntegerField(blank=True, null=True)),
                ('extraction_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('rfc_message_id', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=500, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='NEW', max_length=20)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('email_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('classification_method', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('classification_tokens', models.IntegerField(blank=True, null=True)),
                ('extraction_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('rfc_message_id', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=500, null=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.emaillog')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('teams_sent', models.BooleanField(default=False)),
                ('teams_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.emaillog')),
                ('reply_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.replyemail')),
            ],
        ),
        migrations.CreateModel(
            name='SkipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('skip_reason', models.CharField(max_length=50)),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['skipped_at'], name='core_skiplo_skipped_5b8529_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=20)),
                ('reclassified_as', models.CharField(blank=True, max_length=50, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emaillog')),
                ('reply_email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.replyemail')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_otherr_created_341aea_idx'), models.Index(fields=['review_status'], name='core_otherr_review__1bc4d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderTrackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=20)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emaillog')),
                ('reply_email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.replyemail')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_ordert_status_48e503_idx')],
            },
        ),
        migrations.CreateModel(
            name='COARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacture_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('report_date', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('amendment_reason', models.TextField(blank=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('changes_summary', models.JSONField(blank=True, null=True)),
                ('parent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='core.coarecord')),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coa', to='core.emaillog')),
                ('reply_email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coa', to='core.replyemail')),
            ],
            options={
                'indexes': [models.Index(fields=['lot_number', 'company', 'is_current'], name='core_coarec_lot_num_b1ac24_idx')],
            },
        ),
    ]
