# Generated by Django 5.0 on 2026-05-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherRecord',
        ),
    ]
