# Generated by Django 5.0 on 2026-05-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_coarecord_bol_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='classification_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='extraction_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='total_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
