# Generated by Django 5.0 on 2026-06-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_escalationrecord_reply_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('logger_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emailflow].[AppLog',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='skiplog',
            new_name='emailflow]._skipped_fc16e2_idx',
            old_name='core_skiplo_skipped_5b8529_idx',
        ),
        migrations.AddField(
            model_name='skiplog',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='replyemail',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='emaillog',
            table='emailflow].[EmailLog',
        ),
        migrations.AlterModelTable(
            name='escalationrecord',
            table='emailflow].[EscalationRecord',
        ),
        migrations.AlterModelTable(
            name='replyemail',
            table='emailflow].[ReplyEmail',
        ),
        migrations.AlterModelTable(
            name='skiplog',
            table='emailflow].[SkipLog',
        ),
    ]
